steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--build-arg', 'PROJECT_ID=$PROJECT_ID', '--cache-from', 'gcr.io/$PROJECT_ID/$REPO_NAME:latest', '-t', 'gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA', '-t', 'gcr.io/$PROJECT_ID/$REPO_NAME:latest', '.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA']

  # Replace the image tag in the k8s Deployment
- name: 'ubuntu'
  args: [
    'sed', '-i',
    's|gcr.io/project/example:.*|gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA|g',
    'deployment.yaml'
  ]

- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    gcloud components install kubectl
    gsutil cp gs://cloud-build/flash-gasket-94900-kubernetes.json .
    export GOOGLE_APPLICATION_CREDENTIALS=flash-gasket-94900-kubernetes.json

- name: 'gcr.io/cloud-builders/kubectl'
  env: ['CLOUDSDK_COMPUTE_ZONE=europe-west1-b', 'CLOUDSDK_CONTAINER_CLUSTER=kube']
  args: ['apply', '-f', 'deployment.yaml']

images:
- 'gcr.io/$PROJECT_ID/$REPO_NAME:latest'
